import { Card } from '../types';

export const DEMO_CARDS: Record<string, Card> = {
  ceo: {
    cardId: 'demo-ceo',
    ownerId: 'demo-owner',
    type: 'person',
    slug: 'ceo',
    title: 'Marc Lehmann',
    subtitle: 'Unternehmer & Berater',
    description: 'Strategie. Wachstum. Innovation. Ich begleite Unternehmen in die Zukunft.',
    profileImageUrl: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&q=80&w=1250',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 'c1',
        title: 'Telefon',
        actionType: 'phone',
        actionValue: '+491701234567',
        icon: 'Phone',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 1,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c2',
        title: 'Mail',
        actionType: 'email',
        actionValue: 'marc@lehmann-consulting.de',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 2,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c3',
        title: 'LinkedIn',
        actionType: 'url',
        actionValue: 'https://linkedin.com',
        icon: 'Linkedin',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 3,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c4',
        title: 'Website',
        actionType: 'url',
        actionValue: 'https://lehmann-consulting.de',
        icon: 'Globe',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 4,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c5',
        title: 'Termine',
        actionType: 'url',
        actionValue: 'https://calendly.com',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 5,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c6',
        title: 'WhatsApp',
        actionType: 'whatsapp',
        actionValue: '+491701234567',
        icon: 'MessageSquare',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 6,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c7',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 7,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c8',
        title: 'Video',
        actionType: 'url',
        actionValue: 'https://youtube.com',
        icon: 'Video',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 8,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  },
  autohaus: {
    cardId: 'demo-autohaus',
    ownerId: 'demo-owner',
    type: 'company',
    slug: 'autohaus',
    title: 'Luxoria Motors',
    subtitle: 'AUTOHAUS & PREMIUM SERVICE',
    description: 'Exklusive Fahrzeuge. Persönlicher Service. Leidenschaft, die Sie bewegt.',
    profileImageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=300',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 'a1',
        title: 'Anrufen',
        actionType: 'phone',
        actionValue: '+4989123456',
        icon: 'Phone',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 1,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a2',
        title: 'E-Mail',
        actionType: 'email',
        actionValue: 'info@luxoria-motors.de',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 2,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a3',
        title: 'WhatsApp',
        actionType: 'whatsapp',
        actionValue: '+49170112233',
        icon: 'MessageSquare',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 3,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a4',
        title: 'Fahrzeuge',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/autos',
        icon: 'Car',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 4,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a5',
        title: 'Probefahrt buchen',
        actionType: 'url',
        actionValue: 'https://calendly.com',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 5,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a6',
        title: 'Standort',
        actionType: 'url',
        actionValue: 'https://maps.google.com',
        icon: 'MapPin',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 6,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a7',
        title: 'Service & Werkstatt',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/service',
        icon: 'Wrench',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 7,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a8',
        title: 'Finanzierung & Leasing',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/leasing',
        icon: 'Euro',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 8,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a9',
        title: 'Broschüren Download',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/brochure.pdf',
        icon: 'FileText',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 9,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a10',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 10,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  },
  schwimmverband: {
    cardId: 'demo-schwimmverband',
    ownerId: 'demo-owner',
    type: 'club',
    slug: 'schwimmverband',
    title: 'Schwimmverband Aqua Futura',
    subtitle: 'Stark im Wasser. Gemeinsam im Verein.',
    description: 'Wir fördern den Schwimmsport in allen Altersklassen, unterstützen Talente und stehen für Fairness, Teamgeist und Erfolg.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&q=80&w=300',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=1200',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 's1',
        title: 'Veranstaltungen & Termine',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/events',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 1,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's2',
        title: 'Wettkämpfe & Ergebnisse',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/results',
        icon: 'Waves',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 2,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's3',
        title: 'Mitglied werden & Beiträge',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/join',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 3,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's4',
        title: 'Aktuelles & News',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/news',
        icon: 'FileText',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 4,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's5',
        title: 'Galerie & Impressionen',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/gallery',
        icon: 'Image',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 5,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's6',
        title: 'Kontakt & Ansprechpartner',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/contact',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 6,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's7',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 7,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  }
};
