/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TRANSLATIONS = {
  de: {
    appTitle: "ureel – Aus Video wird Aktion.",
    appSub: "Erstelle mit ureel deinen digitalen Auftritt für dich, dein Unternehmen, dein Produkt, deinen Verein oder dein Projekt – und teile ihn überall mit einem Link.",
    getStarted: "Kostenlos starten",
    login: "Einloggen",
    logout: "Abmelden",
    dashboard: "Nutzer-Dashboard",
    adminArea: "Admin-Bereich",
    profile: "Profil",
    design: "Design",
    buttons: "Buttons",
    files: "Dateien & PDF",
    sharing: "Teilen & QR",
    stats: "Statistiken",
    plans: "Preise & Upgrade",
    settings: "Einstellungen",
    legal: "Rechtliches",
    support: "Support",
    legalAuditedNotice: "Wichtiger Hinweis: Dieser Inhalt dient als Muster und Platzhalter - er muss vor Veröffentlichung juristisch geprüft werden.",
    acceptTerms: "Ich akzeptiere die Allgemeinen Geschäftsbedingungen (AGB).",
    acceptPrivacy: "Ich akzeptiere die Datenschutzerklärung.",
    newsletterOptIn: "Ich möchte den kostenlosen Newsletter abonnieren (freiwillig).",
    submitReport: "Inhalt melden",
    reportSuccess: "Vielen Dank. Die Meldung wurde erfolgreich an unsere Administratoren übermittelt.",
    reportInstruction: "Sollte dieses Profil gegen unsere Richtlinien oder geltendes Recht verstoßen, melden Sie es uns bitte über dieses Formular.",
    saveContact: "In Kontakten speichern",
    saveContactTooltip: "Diese Karte in meinen Kontakten speichern",
    contact: "In Kontakten speichern",
    share: "Teilen",
    createYourOwn: "Eigene ureel erstellen",
    createdWithKonu: "Erstellt mit ureel",
    brandSlogan: "Aus Video wird Aktion.",
    toast_vcardDownloaded: "Kontaktdatei heruntergeladen",
    secureFastReliable: "Sicher. Schnell. Verlässlich.",
    shareOnceAlwaysUpToDate: "Einmal teilen. Immer aktuell.",
    copiedLink: "ureel-Link kopiert",
    downloadQrCode: "QR-Code herunterladen",
    shareQrCode: "QR-Code teilen",
    downloadContactFile: "Kontaktdatei herunterladen",
    reportContent: "Inhalt melden",
    pageNotFound: "Diese ureel-Seite wurde nicht gefunden.",
    pageNotPublic: "Diese ureel-Seite ist derzeit nicht öffentlich verfügbar.",
    loadingPage: "ureel-Seite wird geladen...",
    loadingError: "Beim Laden der ureel-Seite ist ein Fehler aufgetreten.",

    // ButtonDesigner Vocabulary
    editButton: "Button bearbeiten",
    newButton: "Neuer Button",
    preview: "Vorschau",
    text: "Text",
    surface: "Fläche",
    action: "Funktion",
    styling: "Darstellung",
    buttonText: "Buttontext",
    buttonFace: "Buttonoberfläche",
    appearance: "Darstellung",
    backgroundColor: "Hintergrundfarbe",
    textColor: "Textfarbe",
    fontSize: "Schriftgröße",
    fontFamily: "Schriftart",
    fontWeight: "Schriftgewicht",
    textAlignment: "Textausrichtung",
    textPosition: "Textposition",
    uploadImage: "Bild hochladen",
    removeImage: "Bild entfernen",
    imageMode: "Bildmodus",
    overlay: "Abdunklung",
    actionType: "Aktionstyp",
    linkTarget: "Link / Ziel",
    testAction: "Funktion testen",
    uploadFile: "Datei hochladen",
    passwordProtection: "Passwortschutz",
    passwordPin: "Passwort/PIN",
    hintText: "Hinweistext",
    border: "Rahmen",
    borderColor: "Rahmenfarbe",
    borderWidth: "Rahmenstärke",
    cornerRadius: "Rundung",
    shadow: "Schatten",
    icon: "Icon",
    animation: "Animation",
    delete: "Löschen",
    cancel: "Abbrechen",
    save: "Speichern",
    buttonSaved: "Button gespeichert",
    buttonCouldNotBeSaved: "Button konnte nicht gespeichert werden",
    buttonDeleted: "Button gelöscht",
    buttonCouldNotBeDeleted: "Button konnte nicht gelöscht werden",
    discardChanges: "Änderungen verwerfen?",
    unsavedChanges: "Ungespeicherte Änderungen",

    // Action Types
    act_website: "Webseite",
    act_phone: "Telefon",
    act_email: "E-Mail",
    act_whatsapp: "WhatsApp",
    act_sms: "SMS",
    act_instagram: "Instagram",
    act_facebook: "Facebook",
    act_linkedin: "LinkedIn",
    act_youtube: "YouTube",
    act_file: "Datei / PDF",
    act_gallery: "Galerie",
    act_video: "Video",
    act_vcard: "vCard / Kontakt",
    act_custom: "Eigener Link",

    // System Actions
    sys_saveContact: "Kontakt sichern",
    sys_share: "Teilen",
    sys_copyLink: "Link kopieren",
    sys_qrCode: "QR-Code",
    sys_preview: "Vorschau",
    sys_signOut: "Abmelden",
    sys_openPublicPage: "Öffentliche Seite öffnen",
    sys_publish: "Veröffentlichen",
    sys_update: "Aktualisieren",

    // Placeholders & Help Texts
    placeholder_callNow: "z. B. Jetzt anrufen, Website besuchen...",
    placeholder_enterLink: "Link eingeben",
    placeholder_enterPhone: "Telefonnummer eingeben",
    placeholder_enterEmail: "E-Mail-Adresse eingeben",
    placeholder_enterWhatsapp: "WhatsApp Nummer eingeben",
    placeholder_chooseFile: "Datei auswählen",
    placeholder_enterPassword: "Passwort eingeben",
    placeholder_hintVisitors: "Hinweis für Besucher",

    // Toasts & Errors
    toast_saved: "Gespeichert",
    toast_buttonSaved: "Button gespeichert",
    toast_buttonDeleted: "Button gelöscht",
    toast_linkCopied: "Link kopiert",
    toast_qrCreated: "QR-Code erstellt",
    toast_fileUploaded: "Datei hochgeladen",
    toast_fileUploadFailed: "Datei konnte nicht hochgeladen werden",
    toast_noPermission: "Du hast keine Berechtigung",
    toast_validUrl: "Bitte gib eine gültige URL ein",
    toast_passwordIncorrect: "Passwort nicht korrekt",

    // Landingpage / Startseite
    landing_brand: "ureel",
    landing_slogan: "Aus Video wird Aktion.",
    landing_startFree: "Kostenlos starten",
    landing_viewPricing: "Tarife ansehen",
    landing_login: "Login",
    landing_signUp: "Registrieren",
    landing_subtitle: "Digitale Profile, Mini-Webseiten und smarte Visitenkarten",

    liveProfileNotice: "ureel-Seite – immer aktuell",
    saveSuccess: "Änderungen erfolgreich gespeichert!",
    authGoogle: "Mit Google anmelden",
    welcomeBack: "Willkommen zurück!",
    createFirstCard: "Erstelle deine erste ureel-Seite",
    noCardsYet: "Du hast noch keine ureel-Seite erstellt.",
    viewProfile: "Profil ansehen",
    editProfile: "Profil bearbeiten",
    published: "Veröffentlicht",
    draft: "Entwurf",
    visibility: "Sichtbarkeit",
    public: "Öffentlich",
    privateLink: "Ausschließlich privater Link",
    passwordProtected: "Passwortgeschützt",
    passwordPlaceholder: "Passwort eingeben",
    cardType: "Karten-Kategorie",
    backToDashboard: "Zurück zum Dashboard",
    premiumFeature: "Premium-Funktion",
    upgradeRequired: "Für diese Funktion ist ein Upgrade erforderlich.",
    customBackground: "Eigener Bild-Hintergrund",
    customBgLimit: "Bild-Upload ist erst ab dem Starter-Tarif möglich.",
    storageUsed: "Speicherplatz",
    buttonLimitReached: "Limit an Buttons für kostenlosen Tarif erreicht (max. 6 Buttons). Upgrade für unbegrenztes Hinzufügen.",
    addButton: "Button hinzufügen",
    selectIcon: "Icon auswählen",
    buttonTitle: "Button Titel",
    actionValue: "Ziel-URL / Rufnummer / E-Mail",
    goldBorder: "Goldener Rand (Premium)",
    isActive: "Aktiv",
    imageAsBackground: "Bild als Button-Hintergrund",
    textVisible: "Text anzeigen",
    uploadButtonImage: "Eigenes Button-Bild hochladen (max. 500kb)",
    compressing: "Bild wird komprimiert...",
    downloadQr: "QR-Code herunterladen",
    copyLink: "Link kopieren",
    copied: "Kopiert!",
    shareWhatsapp: "Über WhatsApp teilen",
    shareEmail: "Per E-Mail teilen",
    shareSms: "Per SMS teilen",
    reportCard: "Inhalt melden",
    acceptRightsCheckbox: "Ich bestätige, dass ich alle Rechte an den von mir hochgeladenen Bildern, Logos, Texten und Dateien besitze.",
    
    // Admin dashboard
    adminTitle: "Plattform-Administration",
    allUsers: "Alle Benutzer",
    allCards: "Alle ureel-Seiten",
    allReports: "Erhaltene Meldungen",
    sysStats: "Systemstatistiken",
    sysDecls: "Aktionen",
    deactivate: "Deaktivieren",
    activate: "Aktivieren",
    blockUser: "Benutzer sperren",
    changePlan: "Tarif ändern",
    deleteFiles: "Dateien löschen",
    
    // Categories
    cat_person: "Person / Mini-Webseite",
    cat_company: "Unternehmen / Geschäftlich",
    cat_business: "Unternehmen / Gewerbe",
    cat_product: "Produktseite",
    cat_project: "Projektseite",
    cat_family: "Familienseite",
    cat_team: "Teamseite",
    cat_club: "Vereinsseite",
    cat_school: "Schulseite / Hochschule",
    cat_schule: "Schulseite / Bildung",
    cat_restaurant: "Restaurant & Gastronomie",
    cat_event: "Eventseite",
    
    // Premium Benefits
    psychTipTitle: "ureel Premium-Vorteile 🌟",
    psychTipDesc: "Ein klares Profilbild erhöht das Vertrauen signifikant. Platziere deine wichtigsten Kontaktkanäle ganz oben, um Handlungen für Besucher so einfach wie möglich zu machen.",
    psychTipCompetence: "Überzeuge deine Kunden: Nutze den PDF-Upload, um dein Portfolio oder deine Broschüre direkt als exklusives Dokument anzubieten.",
    psychTipExclusivity: "Erreiche treue Kunden durch passwortgeschützte VIP-Bereiche für Stammkunden oder Partner.",
    myCards: "Meine ureels",
    createNewCard: "Neue ureel erstellen",
    editExistingCard: "Bestehende Karte bearbeiten",
    openPublicPage: "Öffentliche Seite öffnen",
    saveCard: "Karte speichern",
    cardSaved: "Karte gespeichert",
    publishCard: "Karte veröffentlichen",
    updateCardLabel: "Karte aktualisieren",
    duplicateCard: "Karte duplizieren",
    deleteCard: "Karte löschen",
    confirmDeleteCard: "Möchtest du diese Karte wirklich löschen?",
    editOrCreateNotice: "Du kannst eine bestehende Karte bearbeiten oder eine neue ureel erstellen.",
    customizeBackgroundLabel: "uReel Editor",
    customizeBackgroundShort: "uReel Editor",
    editProfileSectionLabel: "Texte & Timeline",
    editProfileSectionShort: "Texte & Timeline",
    
    // Password protection translation keys
    passwordLabel: "Passwort",
    passwordRequiredTitle: "Passwort erforderlich",
    passwordPlaceholderText: "Dieser Inhalt ist geschützt. Bitte gib das Passwort ein.",
    passwordHintLabel: "Passwort-Hinweis",
    passwordHelpText: "Besucher müssen dieses Passwort eingeben, bevor sie die Button-Funktion öffnen können.",
    passwordProNotice: "Passwortgeschützte Buttons sind ab ureel Pro verfügbar.",
    passwordInputEmptyError: "Bitte gib ein Passwort ein.",
    passwordMinLengthError: "Das Passwort muss mindestens 4 Zeichen lang sein.",
    passwordIncorrectError: "Das Passwort ist nicht korrekt.",
    passwordNotSetErrorMessage: "Dieser Button ist geschützt, aber es wurde kein Passwort hinterlegt.",
    open: "Öffnen",
    
    // Forms & Fields (Prompt 6B)
    form_pro_only: "Formulare sind ab ureel Pro verfügbar.",
    form_target_email: "Ziel-E-Mail",
    form_subject: "Betreff",
    form_intro_text: "Hinweistext",
    form_target_email_help: "Wenn keine Ziel-E-Mail eingetragen ist, wird die E-Mail der Karte verwendet.",
    contact_title: "Kontakt aufnehmen",
    contact_intro: "Sende eine kurze Nachricht.",
    inquiry_title: "Anfrage senden",
    inquiry_intro: "Sende eine konkrete Anfrage.",
    callback_title: "Rückruf anfordern",
    callback_intro: "Hinterlasse deine Telefonnummer für einen Rückruf.",
    field_name: "Name",
    field_email: "E-Mail",
    field_phone: "Telefonnummer",
    field_phone_optional: "Telefon optional",
    field_preferred_time: "Wunschzeit optional",
    field_message: "Nachricht",
    field_message_optional: "Nachricht optional",
    field_topic: "Worum geht es?",
    btn_prepare_email: "E-Mail vorbereiten",
    btn_prepare_inquiry: "Anfrage vorbereiten",
    btn_prepare_callback: "Rückruf-E-Mail vorbereiten",
    err_name_required: "Bitte gib deinen Namen ein.",
    err_email_required: "Bitte gib deine E-Mail-Adresse ein.",
    err_message_required: "Bitte schreibe eine Nachricht.",
    err_email_invalid: "Bitte gib eine gültige E-Mail-Adresse ein.",
    err_phone_required: "Bitte gib deine Telefonnummer ein.",
    err_phone_invalid: "Bitte gib eine gültige Telefonnummer ein.",
    err_no_target_email: "Für dieses Formular ist keine Ziel-E-Mail hinterlegt.",
    privacy_notice: "Deine Eingaben werden nicht automatisch in ureel gespeichert. Es wird eine E-Mail in deinem E-Mail-Programm vorbereitet.",
    err_topic_required: "Bitte gib an, worum es geht.",
    
    // Prompt 6C
    brandingSectionTitle: "ureel Branding",
    brandingToggleLabel: "ureel Branding auf öffentlicher Karte ausblenden",
    brandingLockedHint: "Das ureel Branding kann ab ureel Pro ausgeblendet werden.",
    brandingProOnlyUpgrade: "Branding ausblenden ist ab ureel Pro verfügbar.",
    
    analyticsSectionTitle: "Besucherstatistik",
    analyticsTotalViews: "Gesamtaufrufe",
    analyticsToday: "Heute",
    analyticsButtonClicks: "Button-Klicks",
    analyticsLast7Days: "Letzte 7 Tage",
    analyticsTopButtons: "Top-Buttons",
    analyticsNoDataYet: "Noch keine Statistikdaten vorhanden.",
    analyticsProOnlyUpgrade: "Besucherstatistiken sind ab ureel Pro verfügbar.",
    
    qrDownloadTitle: "QR-Code herunterladen",
    qrDownloadPng: "QR-Code als PNG",
    qrDownloadSvg: "QR-Code als SVG",
    vcardDownload: "vCard herunterladen",
    copyLinkAsText: "Link als Text kopieren",
    copyShareText: "Teilen-Text kopieren",
    exportProOnlyUpgrade: "Erweiterte QR- und Exportoptionen sind ab ureel Pro verfügbar.",
    featureProOnlyUpgradeGeneric: "Diese Funktion ist ab ureel Pro verfügbar.",
    fallbackShareTextPrefix: "Hier ist meine ureel-Seite: "
  },
  en: {
    appTitle: "ureel – Turn Video into Action.",
    appSub: "Create your digital presence with ureel for yourself, your business, product, club, or project – and share it anywhere with a single link.",
    getStarted: "Get Started Free",
    login: "Log In",
    logout: "Log Out",
    dashboard: "User Dashboard",
    adminArea: "Admin Area",
    profile: "Profile",
    design: "Design",
    buttons: "Buttons",
    files: "Files & PDF",
    sharing: "Sharing & QR",
    stats: "Statistics",
    plans: "Plans & Upgrade",
    settings: "Settings",
    legal: "Legal Info",
    support: "Support",
    legalAuditedNotice: "Important notice: This content is a template placeholder - it must be legally audited before publication.",
    acceptTerms: "I accept the General Terms and Conditions (AGB).",
    acceptPrivacy: "I accept the Privacy Policy (Datenschutzerklärung).",
    newsletterOptIn: "I want to subscribe to the free newsletter (optional).",
    submitReport: "Report Content",
    reportSuccess: "Thank you. Your report has been successfully transmitted to our administrators.",
    reportInstruction: "If this profile breaches our terms, guidelines, or applicable law, please let us know using this form.",
    saveContact: "Save to contacts",
    saveContactTooltip: "Save this card to my contacts",
    contact: "Save to contacts",
    share: "Share",
    createYourOwn: "Create your own ureel",
    createdWithKonu: "Created with ureel",
    brandSlogan: "Turn Video into Action.",
    toast_vcardDownloaded: "Contact file downloaded",
    secureFastReliable: "Secure. Fast. Reliable.",
    shareOnceAlwaysUpToDate: "Share once. Always up to date.",
    copiedLink: "ureel link copied",
    downloadQrCode: "Download QR code",
    shareQrCode: "Share QR code",
    downloadContactFile: "Download contact file",
    reportContent: "Report content",
    pageNotFound: "This ureel page was not found.",
    pageNotPublic: "This ureel page is currently not public.",
    loadingPage: "Loading ureel page...",
    loadingError: "Something went wrong while loading this ureel page.",

    // ButtonDesigner Vocabulary
    editButton: "Edit button",
    newButton: "New button",
    preview: "Preview",
    text: "Text",
    surface: "Face",
    action: "Action",
    styling: "Style",
    buttonText: "Button text",
    buttonFace: "Button face",
    appearance: "Appearance",
    backgroundColor: "Background color",
    textColor: "Text color",
    fontSize: "Font size",
    fontFamily: "Font family",
    fontWeight: "Font weight",
    textAlignment: "Text alignment",
    textPosition: "Text position",
    uploadImage: "Upload image",
    removeImage: "Remove image",
    imageMode: "Image mode",
    overlay: "Overlay",
    actionType: "Action type",
    linkTarget: "Link / target",
    testAction: "Test action",
    uploadFile: "Upload file",
    passwordProtection: "Password protection",
    passwordPin: "Password/PIN",
    hintText: "Hint text",
    border: "Border",
    borderColor: "Border color",
    borderWidth: "Border width",
    cornerRadius: "Corner radius",
    shadow: "Shadow",
    icon: "Icon",
    animation: "Animation",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    buttonSaved: "Button saved",
    buttonCouldNotBeSaved: "Button could not be saved",
    buttonDeleted: "Button deleted",
    buttonCouldNotBeDeleted: "Button could not be deleted",
    discardChanges: "Discard changes?",
    unsavedChanges: "Unsaved changes",

    // Action Types
    act_website: "Website",
    act_phone: "Phone",
    act_email: "Email",
    act_whatsapp: "WhatsApp",
    act_sms: "SMS",
    act_instagram: "Instagram",
    act_facebook: "Facebook",
    act_linkedin: "LinkedIn",
    act_youtube: "YouTube",
    act_file: "File / PDF",
    act_gallery: "Gallery",
    act_video: "Video",
    act_vcard: "vCard / Contact",
    act_custom: "Custom link",

    // System Actions
    sys_saveContact: "Save contact",
    sys_share: "Share",
    sys_copyLink: "Copy link",
    sys_qrCode: "QR code",
    sys_preview: "Preview",
    sys_signOut: "Sign out",
    sys_openPublicPage: "Open public page",
    sys_publish: "Publish",
    sys_update: "Update",

    // Placeholders & Help Texts
    placeholder_callNow: "e.g. Call now, visit website...",
    placeholder_enterLink: "Enter link",
    placeholder_enterPhone: "Enter phone number",
    placeholder_enterEmail: "Enter email address",
    placeholder_enterWhatsapp: "Enter WhatsApp number",
    placeholder_chooseFile: "Choose file",
    placeholder_enterPassword: "Enter password",
    placeholder_hintVisitors: "Hint for visitors",

    // Toasts & Errors
    toast_saved: "Saved",
    toast_buttonSaved: "Button saved",
    toast_buttonDeleted: "Button deleted",
    toast_linkCopied: "Link copied",
    toast_qrCreated: "QR code created",
    toast_fileUploaded: "File uploaded",
    toast_fileUploadFailed: "File could not be uploaded",
    toast_noPermission: "You do not have permission",
    toast_validUrl: "Please enter a valid URL",
    toast_passwordIncorrect: "Incorrect password",

    // Landingpage / Startseite
    landing_brand: "ureel",
    landing_slogan: "Turn Video into Action.",
    landing_startFree: "Start for free",
    landing_viewPricing: "View pricing",
    landing_login: "Login",
    landing_signUp: "Sign up",
    landing_subtitle: "Digital profiles, mini websites and smart business cards",

    liveProfileNotice: "ureel Page – Always Current",
    saveSuccess: "Changes saved successfully!",
    authGoogle: "Sign In with Google",
    welcomeBack: "Welcome back!",
    createFirstCard: "Create your first ureel page",
    noCardsYet: "You have not created a ureel page yet.",
    viewProfile: "View Profile",
    editProfile: "Edit Profile",
    published: "Published",
    draft: "Draft",
    visibility: "Visibility",
    public: "Public",
    privateLink: "Private Link Only",
    passwordProtected: "Password Protected",
    passwordPlaceholder: "Enter password",
    cardType: "Card Category",
    backToDashboard: "Back to Dashboard",
    premiumFeature: "Premium Feature",
    upgradeRequired: "This feature requires an upgrade.",
    customBackground: "Custom Image Background",
    customBgLimit: "Image background uploads are available on Starter and higher plans.",
    storageUsed: "Storage Space",
    buttonLimitReached: "Your plan's button limit has been reached (max 6 buttons for Free). Upgrade to unlock unlimited buttons.",
    addButton: "Add Button",
    selectIcon: "Select Icon",
    buttonTitle: "Button Title",
    actionValue: "Target URL / Phone / Email",
    goldBorder: "Gold Border (Premium)",
    isActive: "Active",
    imageAsBackground: "Image as Button Background",
    textVisible: "Show Text",
    uploadButtonImage: "Upload custom outer image (max 500kb)",
    compressing: "Compressing image...",
    downloadQr: "Download QR Code",
    copyLink: "Copy Link",
    copied: "Copied!",
    shareWhatsapp: "Share via WhatsApp",
    shareEmail: "Share via Email",
    shareSms: "Share via SMS",
    reportCard: "Report Profile",
    acceptRightsCheckbox: "I declare that I own all rights to the uploaded images, logos, texts, and files.",
    
    // Admin dashboard
    adminTitle: "Platform Administration",
    allUsers: "All Users",
    allCards: "All ureel Pages",
    allReports: "Abuse Reports",
    sysStats: "System Statistics",
    sysDecls: "Actions",
    deactivate: "Deactivate",
    activate: "Activate",
    blockUser: "Block User",
    changePlan: "Change Plan",
    deleteFiles: "Delete Files",
    
    // Categories
    cat_person: "Person / Digital Business Card",
    cat_company: "Corporate / Business Info",
    cat_business: "Small Business / Commerce",
    cat_product: "Product Showroom",
    cat_project: "Project Page",
    cat_family: "Family Card",
    cat_team: "Team Card",
    cat_club: "Club / Association Card",
    cat_school: "School / Education",
    cat_schule: "School / Learning Info",
    cat_restaurant: "Restaurant & Gastronomy",
    cat_event: "Event Invitation",
    
    // Premium Benefits
    psychTipTitle: "ureel Premium Benefits 🌟",
    psychTipDesc: "A clear profile picture significantly increases trust. Place your most important contact channels at the top to make actions as easy as possible for visitors.",
    psychTipCompetence: "Convince your clients: Use the PDF upload to offer your portfolio or brochure directly as an exclusive document.",
    psychTipExclusivity: "Engage loyal clients with password-restricted VIP zones for regular clients or partners.",
    myCards: "My ureels",
    createNewCard: "Create new ureel",
    editExistingCard: "Edit existing card",
    openPublicPage: "Open public page",
    saveCard: "Save card",
    cardSaved: "Card saved",
    publishCard: "Publish card",
    updateCardLabel: "Update card",
    duplicateCard: "Duplicate card",
    deleteCard: "Delete card",
    confirmDeleteCard: "Do you really want to delete this card?",
    editOrCreateNotice: "You can edit an existing card or create a new ureel.",
    customizeBackgroundLabel: "uReel Editor",
    customizeBackgroundShort: "uReel Editor",
    editProfileSectionLabel: "Texts & Timeline",
    editProfileSectionShort: "Texts & Timeline",
    
    // Password protection translation keys
    passwordLabel: "Password",
    passwordRequiredTitle: "Password required",
    passwordPlaceholderText: "This content is protected. Please enter the password.",
    passwordHintLabel: "Password hint",
    passwordHelpText: "Visitors must enter this password before they can open the button action.",
    passwordProNotice: "Password-protected buttons are available from ureel Pro.",
    passwordInputEmptyError: "Please enter a password.",
    passwordMinLengthError: "The password must be at least 4 characters long.",
    passwordIncorrectError: "The password is not correct.",
    passwordNotSetErrorMessage: "This button is protected, but no password has been set.",
    open: "Open",
    
    // Forms & Fields (Prompt 6B)
    form_pro_only: "Forms are available from ureel Pro.",
    form_target_email: "Target email",
    form_subject: "Subject",
    form_intro_text: "Intro text",
    form_target_email_help: "If no target email is entered, the card email will be used.",
    contact_title: "Get in touch",
    contact_intro: "Send a short message.",
    inquiry_title: "Send inquiry",
    inquiry_intro: "Send a specific inquiry.",
    callback_title: "Request callback",
    callback_intro: "Leave your phone number for a callback.",
    field_name: "Name",
    field_email: "Email",
    field_phone: "Phone number",
    field_phone_optional: "Phone optional",
    field_preferred_time: "Preferred time optional",
    field_message: "Message",
    field_message_optional: "Message optional",
    field_topic: "What is it about?",
    btn_prepare_email: "Prepare email",
    btn_prepare_inquiry: "Prepare inquiry",
    btn_prepare_callback: "Prepare callback email",
    err_name_required: "Please enter your name.",
    err_email_required: "Please enter your email address.",
    err_message_required: "Please write a message.",
    err_email_invalid: "Please enter a valid email address.",
    err_phone_required: "Please enter your phone number.",
    err_phone_invalid: "Please enter a valid phone number.",
    err_no_target_email: "No target email has been set for this form.",
    privacy_notice: "Your entries are not automatically stored in ureel. An email will be prepared in your email app.",
    err_topic_required: "Please specify what it is about.",
    
    // Prompt 6C
    brandingSectionTitle: "ureel branding",
    brandingToggleLabel: "Hide ureel branding on public card",
    brandingLockedHint: "ureel branding can be hidden from ureel Pro.",
    brandingProOnlyUpgrade: "Hiding branding is available from ureel Pro.",
    
    analyticsSectionTitle: "Visitor statistics",
    analyticsTotalViews: "Total views",
    analyticsToday: "Today",
    analyticsButtonClicks: "Button clicks",
    analyticsLast7Days: "Last 7 days",
    analyticsTopButtons: "Top buttons",
    analyticsNoDataYet: "No statistics data yet.",
    analyticsProOnlyUpgrade: "Visitor statistics are available from ureel Pro.",
    
    qrDownloadTitle: "Download QR code",
    qrDownloadPng: "QR code as PNG",
    qrDownloadSvg: "QR code as SVG",
    vcardDownload: "Download vCard",
    copyLinkAsText: "Copy link as text",
    copyShareText: "Copy share text",
    exportProOnlyUpgrade: "Advanced QR and export options are available from ureel Pro.",
    featureProOnlyUpgradeGeneric: "This feature is available from ureel Pro.",
    fallbackShareTextPrefix: "Here is my ureel page: "
  }
};
