import { Card } from '../types';

export const DEMO_CARDS: Record<string, Card> = {
  ceo: {
    cardId: 'demo-ceo',
    ownerId: 'demo-owner',
    type: 'person',
    slug: 'ceo',
    title: 'Marc Lehmann',
    subtitle: 'Unternehmer & Berater',
    description: 'Strategie. Wachstum. Innovation. Ich begleite Unternehmen in die Zukunft.',
    profileImageUrl: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&q=80&w=1250',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 'c1',
        title: 'Telefon',
        actionType: 'phone',
        actionValue: '+491701234567',
        icon: 'Phone',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 1,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c2',
        title: 'Mail',
        actionType: 'email',
        actionValue: 'marc@lehmann-consulting.de',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 2,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c3',
        title: 'LinkedIn',
        actionType: 'url',
        actionValue: 'https://linkedin.com',
        icon: 'Linkedin',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 3,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c4',
        title: 'Website',
        actionType: 'url',
        actionValue: 'https://lehmann-consulting.de',
        icon: 'Globe',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 4,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c5',
        title: 'Termine',
        actionType: 'url',
        actionValue: 'https://calendly.com',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 5,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c6',
        title: 'WhatsApp',
        actionType: 'whatsapp',
        actionValue: '+491701234567',
        icon: 'MessageSquare',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 6,
        isActive: true,
        bgColor: '#161616',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c7',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 7,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      },
      {
        id: 'c8',
        title: 'Video',
        actionType: 'url',
        actionValue: 'https://youtube.com',
        icon: 'Video',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 8,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  },
  autohaus: {
    cardId: 'demo-autohaus',
    ownerId: 'demo-owner',
    type: 'company',
    slug: 'autohaus',
    title: 'Luxoria Motors',
    subtitle: 'AUTOHAUS & PREMIUM SERVICE',
    description: 'Exklusive Fahrzeuge. Persönlicher Service. Leidenschaft, die Sie bewegt.',
    profileImageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=300',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 'a1',
        title: 'Anrufen',
        actionType: 'phone',
        actionValue: '+4989123456',
        icon: 'Phone',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 1,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a2',
        title: 'E-Mail',
        actionType: 'email',
        actionValue: 'info@luxoria-motors.de',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 2,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a3',
        title: 'WhatsApp',
        actionType: 'whatsapp',
        actionValue: '+49170112233',
        icon: 'MessageSquare',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 3,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a4',
        title: 'Fahrzeuge',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/autos',
        icon: 'Car',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 4,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a5',
        title: 'Probefahrt buchen',
        actionType: 'url',
        actionValue: 'https://calendly.com',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 5,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a6',
        title: 'Standort',
        actionType: 'url',
        actionValue: 'https://maps.google.com',
        icon: 'MapPin',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 6,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a7',
        title: 'Service & Werkstatt',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/service',
        icon: 'Wrench',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 7,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a8',
        title: 'Finanzierung & Leasing',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/leasing',
        icon: 'Euro',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 8,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a9',
        title: 'Broschüren Download',
        actionType: 'url',
        actionValue: 'https://luxoria-motors.de/brochure.pdf',
        icon: 'FileText',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'pill',
        position: 9,
        isActive: true,
        bgColor: '#141414',
        textColor: '#A855F7',
        borderColor: '#A855F7'
      },
      {
        id: 'a10',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 10,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  },
  schwimmverband: {
    cardId: 'demo-schwimmverband',
    ownerId: 'demo-owner',
    type: 'club',
    slug: 'schwimmverband',
    title: 'Schwimmverband Aqua Futura',
    subtitle: 'Stark im Wasser. Gemeinsam im Verein.',
    description: 'Wir fördern den Schwimmsport in allen Altersklassen, unterstützen Talente und stehen für Fairness, Teamgeist und Erfolg.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&q=80&w=300',
    backgroundType: 'image',
    backgroundImageUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=1200',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    buttons: [
      {
        id: 's1',
        title: 'Veranstaltungen & Termine',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/events',
        icon: 'Calendar',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 1,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's2',
        title: 'Wettkämpfe & Ergebnisse',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/results',
        icon: 'Waves',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 2,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's3',
        title: 'Mitglied werden & Beiträge',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/join',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 3,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's4',
        title: 'Aktuelles & News',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/news',
        icon: 'FileText',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 4,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's5',
        title: 'Galerie & Impressionen',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/gallery',
        icon: 'Image',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 5,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's6',
        title: 'Kontakt & Ansprechpartner',
        actionType: 'url',
        actionValue: 'https://aqua-futura.de/contact',
        icon: 'Mail',
        iconEnabled: true,
        styleVariant: 'filled',
        radius: 'rounded',
        position: 6,
        isActive: true,
        bgColor: '#062c43',
        textColor: '#e2f1f8',
        borderColor: '#A855F7'
      },
      {
        id: 's7',
        title: 'In Kontakten speichern',
        actionType: 'vcard',
        actionValue: '',
        icon: 'UserPlus',
        iconEnabled: true,
        styleVariant: 'outline',
        radius: 'rounded',
        position: 7,
        isActive: true,
        bgColor: 'transparent',
        textColor: '#FFFFFF',
        borderColor: '#A855F7'
      }
    ]
  },
  'dein-angebot-sofort-klickbar': {
    cardId: 'demo-landing-nadine-jersey',
    ownerId: 'demo-owner',
    type: 'person',
    slug: 'dein-angebot-sofort-klickbar',
    title: 'Nadine Jersey',
    subtitle: 'Unternehmensberaterin',
    description: 'Beratung klar präsentieren. Ein professionelles Reel wird zur strukturierten Vorstellung mit Angebot, Kontakt und Termin.',
    profileImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'video',
    backgroundColor: '#15110D',
    backgroundImageUrl: 'https://img.youtube.com/vi/phgVor0F9Xw/hqdefault.jpg',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    companyName: 'Strategie sichtbar machen',
    location: 'Beratung. Vertrauen. Kontakt.',
    category: 'consulting',
    videoBackgroundConfig: {
      enabled: true,
      mode: 'youtube',
      mediaMode: 'youtube',
      youtubeUrl: 'https://youtube.com/shorts/phgVor0F9Xw?feature=share',
      startTimeSeconds: 4,
      durationSeconds: 12,
      videoFitMode: 'cover',
      youtube: { url: 'https://youtube.com/shorts/phgVor0F9Xw?feature=share', startTimeSeconds: 4, mute: true }
    },
    buttons: [
      { id: 'nadine-website', title: 'Website besuchen', actionType: 'url', actionValue: 'https://www.ureel.me', icon: 'Globe', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 1, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'nadine-phone', title: 'Anrufen', actionType: 'phone', actionValue: '+431234567', icon: 'Phone', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 2, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'nadine-calendar', title: 'Termin vereinbaren', actionType: 'url', actionValue: 'https://calendly.com', icon: 'Calendar', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 3, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'nadine-mail', title: 'E-Mail schreiben', actionType: 'email', actionValue: 'office@example.com', icon: 'Mail', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 4, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' }
    ]
  },
  'dein-angebot-sofort-klickbar-6': {
    cardId: 'demo-landing-mx9',
    ownerId: 'demo-owner',
    type: 'product',
    slug: 'dein-angebot-sofort-klickbar-6',
    title: 'MX9',
    subtitle: 'Automarke',
    description: 'Der neue MX9. Top Performance, pure Electric und ein direkter Weg zu Anfrage, Probefahrt und Kontakt.',
    profileImageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'video',
    backgroundColor: '#090909',
    backgroundImageUrl: 'https://img.youtube.com/vi/UQEDw9BCDPo/hqdefault.jpg',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    companyName: 'Der neue MX9',
    location: 'Top Performance. Pure Electric.',
    category: 'auto',
    videoBackgroundConfig: {
      enabled: true,
      mode: 'youtube',
      mediaMode: 'youtube',
      youtubeUrl: 'https://youtube.com/shorts/UQEDw9BCDPo?feature=share',
      startTimeSeconds: 4,
      durationSeconds: 12,
      videoFitMode: 'cover',
      youtube: { url: 'https://youtube.com/shorts/UQEDw9BCDPo?feature=share', startTimeSeconds: 4, mute: true }
    },
    buttons: [
      { id: 'mx9-highlights', title: 'Highlights ansehen', actionType: 'url', actionValue: 'https://www.ureel.me', icon: 'Sparkles', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 1, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'mx9-probefahrt', title: 'Probefahrt buchen', actionType: 'url', actionValue: 'https://calendly.com', icon: 'Calendar', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 2, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'mx9-phone', title: 'Anrufen', actionType: 'phone', actionValue: '+431234567', icon: 'Phone', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 3, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'mx9-mail', title: 'Anfrage senden', actionType: 'email', actionValue: 'sales@example.com', icon: 'Mail', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 4, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' }
    ]
  },
  'dein-angebot-sofort-klickbar-4': {
    cardId: 'demo-landing-irene-hager',
    ownerId: 'demo-owner',
    type: 'company',
    slug: 'dein-angebot-sofort-klickbar-4',
    title: 'Irene Hager',
    subtitle: 'Tischlerei',
    description: 'Handwerk sichtbar machen. Eine moderne Präsentation für Maßarbeit, Referenzen, Kurse und direkte Anfrage.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'video',
    backgroundColor: '#130F0A',
    backgroundImageUrl: 'https://img.youtube.com/vi/nJi-Fl3u57o/hqdefault.jpg',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    companyName: 'Möbelmanufaktur',
    location: 'Von Hand gefertigt',
    category: 'craft',
    videoBackgroundConfig: {
      enabled: true,
      mode: 'youtube',
      mediaMode: 'youtube',
      youtubeUrl: 'https://youtube.com/shorts/nJi-Fl3u57o?feature=share',
      startTimeSeconds: 4,
      durationSeconds: 12,
      videoFitMode: 'cover',
      youtube: { url: 'https://youtube.com/shorts/nJi-Fl3u57o?feature=share', startTimeSeconds: 4, mute: true }
    },
    buttons: [
      { id: 'irene-works', title: 'Arbeiten ansehen', actionType: 'url', actionValue: 'https://www.ureel.me', icon: 'Image', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 1, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'irene-request', title: 'Anfrage senden', actionType: 'email', actionValue: 'werkstatt@example.com', icon: 'Mail', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 2, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'irene-phone', title: 'Anrufen', actionType: 'phone', actionValue: '+431234567', icon: 'Phone', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 3, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'irene-course', title: 'Kurs buchen', actionType: 'url', actionValue: 'https://calendly.com', icon: 'Calendar', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 4, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' }
    ]
  },
  'your-offer-instantly-clickable': {
    cardId: 'demo-landing-jennifer-lawson',
    ownerId: 'demo-owner',
    type: 'person',
    slug: 'your-offer-instantly-clickable',
    title: 'Jennifer Lawson',
    subtitle: 'Studentin',
    description: 'Portfolio und Kontakt in Sekunden. Eine persönliche Präsentation für Studium, Bewerbung und Netzwerk.',
    profileImageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400',
    backgroundType: 'video',
    backgroundColor: '#111111',
    backgroundImageUrl: 'https://img.youtube.com/vi/VF41Qhgy7ik/hqdefault.jpg',
    backgroundImageFit: 'cover',
    overlay: 'dark',
    isPublished: true,
    visibility: 'public',
    brandingRequired: false,
    companyName: 'Portfolio & Kontakt',
    location: 'Studentin mit Profil',
    category: 'student',
    videoBackgroundConfig: {
      enabled: true,
      mode: 'youtube',
      mediaMode: 'youtube',
      youtubeUrl: 'https://youtube.com/shorts/VF41Qhgy7ik?feature=share',
      startTimeSeconds: 4,
      durationSeconds: 12,
      videoFitMode: 'cover',
      youtube: { url: 'https://youtube.com/shorts/VF41Qhgy7ik?feature=share', startTimeSeconds: 4, mute: true }
    },
    buttons: [
      { id: 'jennifer-portfolio', title: 'Portfolio ansehen', actionType: 'url', actionValue: 'https://www.ureel.me', icon: 'BriefcaseBusiness', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 1, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'jennifer-mail', title: 'Kontakt aufnehmen', actionType: 'email', actionValue: 'hello@example.com', icon: 'Mail', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 2, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'jennifer-linkedin', title: 'LinkedIn', actionType: 'url', actionValue: 'https://linkedin.com', icon: 'Linkedin', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 3, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' },
      { id: 'jennifer-cv', title: 'Lebenslauf', actionType: 'pdf_link', actionValue: 'https://www.ureel.me', icon: 'FileText', iconEnabled: true, styleVariant: 'filled', radius: 'rounded', position: 4, isActive: true, bgColor: '#171717', textColor: '#FFFFFF', borderColor: '#F2D28B' }
    ]
  }
};
